[package]
name = "seqhash"
version = "0.2.0"
edition = "2021"
license = "MIT"
author = "Noam Teyssier <noam.teyssier@arcinstitute.org>"
description = "Fast mismatch-tolerant sequence lookup with disambiguation"
repository = "https://github.com/noamteyssier/seqhash"
categories = ["science::bioinformatics"]
keywords = ["sequencing", "genomics", "hashing", "mismatch", "hamming"]

[features]
default = ["parallel"]
serde = ["dep:serde", "dep:bincode", "hashbrown/serde"]
parallel = ["parking_lot", "num_cpus"]

[dependencies]
hashbrown = "0.16"
fxhash = "0.2"
serde = { version = "1", features = ["derive"], optional = true }
bincode = { version = "3", optional = true }
parking_lot = {version = "0.12.5", optional = true }
num_cpus = {version = "1.17.0", optional = true}

[dev-dependencies]
criterion = "0.8"
rand = "0.9"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
ahash = "0.8"
wyhash = "0.6"
serde_json = "1"
clap = { version = "4.5.54", features = ["derive"] }
anyhow = "1.0.100"
binseq = "0.9.0"
env_logger = "0.11.8"
log = "0.4.29"

[profile.release]
# debug = true

[[bench]]
name = "seqhash_bench"
harness = false
